services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - /media/renderws/carltonData/cjDbData/2025/nextjs-better-auth:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
